from app.ui.buttons import (
    ADMIN_BOOKINGS,
    BACK,
    BOOK,
    CLIENTS,
    CONTACTS,
    DEV_ADMIN,
    DEV_DIAGNOSTICS,
    HOME,
    YCLIENTS_INTEGRATION,
    YCHECK,
    MESSAGES,
    NOTIFICATIONS,
    STATISTICS,
    MY_BOOKINGS,
    PERSONNEL,
    SETTINGS,
    BROADCAST,
    SUPPORT,
    LOYALTY,
)
from app.ui.texts import FALLBACK_MESSAGE, MAIN_MENU_PROMPT

MAIN_MENU_BTN = HOME
BACK_BTN = BACK

CONTACTS_BTN = CONTACTS
BOOK_APPOINTMENT_BTN = BOOK
BOOK_TABLE_BTN = BOOK  # Backward-compatible label for legacy booking handler.
MY_APPOINTMENTS_BTN = MY_BOOKINGS
SUPPORT_BTN = SUPPORT

ADMIN_APPOINTMENTS_BTN = ADMIN_BOOKINGS
CLIENTS_BTN = CLIENTS
PERSONNEL_BTN = PERSONNEL
SETTINGS_BTN = SETTINGS
MESSAGES_BTN = MESSAGES
NOTIFICATIONS_BTN = NOTIFICATIONS
STATISTICS_BTN = STATISTICS
BROADCAST_BTN = BROADCAST

DEV_DIAGNOSTICS_BTN = DEV_DIAGNOSTICS
DEV_ADMIN_PANEL_BTN = DEV_ADMIN
YCHECK_BTN = YCHECK
YCLIENTS_INTEGRATION_BTN = YCLIENTS_INTEGRATION

# Contact screen labels used by app.core.screens.
OUR_ADDRESS_TEXT = "📍 Наш адрес"
BOOKING_PHONE_TEXT = "📞 Телефон для записи"
BUILD_ROUTE_TEXT = "🗺 Построить маршрут"

LOYALTY_BTN = LOYALTY
